CREATE TABLE IF NOT EXISTS block_requests (
    id VARCHAR(50) PRIMARY KEY,
    department VARCHAR(20) REFERENCES departments(code),
    department_name VARCHAR(100),
    system_name VARCHAR(20),
    status VARCHAR(30) NOT NULL DEFAULT 'SUBMITTED',
    priority VARCHAR(20) NOT NULL DEFAULT 'NORMAL',
    urgency VARCHAR(30) NOT NULL,
    corridor VARCHAR(255) NOT NULL,
    block_section VARCHAR(255) NOT NULL,
    from_location VARCHAR(150) NOT NULL,
    to_location VARCHAR(150) NOT NULL,
    line VARCHAR(20) NOT NULL,
    chainage VARCHAR(100),
    asset_type VARCHAR(100),
    asset_id VARCHAR(100),
    asset_condition VARCHAR(50),
    defect_reason TEXT,
    maintenance_type VARCHAR(200),
    description TEXT,
    requested_date DATE NOT NULL,
    preferred_date DATE NOT NULL,
    preferred_start_time TIME NOT NULL,
    preferred_end_time TIME NOT NULL,
    duration_formatted VARCHAR(50),
    duration_minutes_total INT NOT NULL,
    requested_by VARCHAR(100) NOT NULL,
    designation VARCHAR(100) NOT NULL,
    contact_number VARCHAR(20) NOT NULL,
    operational_requirements JSONB DEFAULT '[]'::jsonb,
    equipment_required JSONB DEFAULT '[]'::jsonb,
    team_size INT DEFAULT 1,
    safety_requirements JSONB DEFAULT '[]'::jsonb,
    remarks TEXT,
    timeline JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
